### ISSUE TITLE
(index) Rare IOOB Exception when excluding a term that isn't known to the lexicon

### ISSUE THREAD

**Issue by vlofgren** [MarginaliaSearch/MarginaliaSearch#37]
```
 java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
  at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:341) ~[fastutil-8.5.8.jar:?]
  at nu.marginalia.index.svc.IndexQueryService.logSearchTerms(IndexQueryService.java:239) ~[index-service.jar:?]
  at nu.marginalia.index.svc.IndexQueryService.evaluateSubqueries(IndexQueryService.java:183) ~[index-service.jar:?]
  at nu.marginalia.index.svc.IndexQueryService.executeSearch(IndexQueryService.java:131) ~[index-service.jar:?]
  at nu.marginalia.index.svc.IndexQueryService.lambda$search$0(IndexQueryService.java:87) ~[index-service.jar:?]
```

Seems to happen with - or ? terms that refer to keywords that aren't known to the system.

**Comment by vlofgren** [comment]
Fixed with cb55c766640591ce9971b69f2fb4cc55f1410d3b
